module.exports = {
  input: {
    width: "100%",
    height: "40px",
    lineHeight: "30px",
    padding: "0 6px 0 8px",
    border: "1px solid #ccc",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
  inputDisabled: {
    width: "100%",
    height: "40px",
    lineHeight: "30px",
    padding: "0 6px 0 8px",
    border: "1px solid #ccc",
    cursor: "auto",
    backgroundColor: "#f4f4f4",
  },
  inputFocused: {
    width: "100%",
    height: "40px",
    lineHeight: "30px",
    padding: "0 6px 0 8px",
    border: "1px solid #ccc",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
  inputHovered: {
    width: "100%",
    height: "40px",
    lineHeight: "30px",
    padding: "0 6px 0 8px",
    border: "1px solid #ccc",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
  inputHoveredFocused: {
    width: "100%",
    height: "40px",
    lineHeight: "30px",
    padding: "0 6px 0 8px",
    border: "1px solid #ccc",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
}
